services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8000:8000
        depends_on:
            - db

    db:
        image: mysql
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
        volumes:
            - ./data:/var/lib/mysql

